export declare function arabic(word: string): string
export declare function armenian(word: string): string
export declare function bulgarian(word: string): string
export declare function danish(word: string): string
export declare function dutch(word: string): string
export declare function english(word: string): string
export declare function finnish(word: string): string
export declare function french(word: string): string
export declare function german(word: string): string
export declare function greek(word: string): string
export declare function hungarian(word: string): string
export declare function indian(word: string): string
export declare function indonesian(word: string): string
export declare function irish(word: string): string
export declare function italian(word: string): string
export declare function lithuanian(word: string): string
export declare function nepali(word: string): string
export declare function norwegian(word: string): string
export declare function portuguese(word: string): string
export declare function romanian(word: string): string
export declare function russian(word: string): string
export declare function serbian(word: string): string
export declare function slovenian(word: string): string
export declare function spanish(word: string): string
export declare function swedish(word: string): string
export declare function turkish(word: string): string
export declare function ukrainian(word: string): string
