export type Language = typeof SUPPORTED_LANGUAGES[number];

export const SUPPORTED_LANGUAGES = [
  "arabic",
  "armenian",
  "dutch",
  "english",
  "french",
  "greek",
  "indonesian",
  "italian",
  "irish",
  "indian",
  "lithuanian",
  "nepali",
  "norwegian",
  "portuguese",
  "russian",
  "spanish",
  "swedish",
  "german",
  "finnish",
  "danish",
  "hungarian",
  "romanian",
  "serbian",
  "turkish",
] as const;
