export { create } from './methods/create.ts'
export { count, getByID } from './methods/docs.ts'
export { insert, insertMultiple } from './methods/insert.ts'
export { remove, removeMultiple } from './methods/remove.ts'
export { search } from './methods/search.ts'
export { searchVector } from './methods/search-vector.ts'
export { load, save } from './methods/serialization.ts'
export { update, updateMultiple } from './methods/update.ts'

export * from './types.ts'
export * as components from './components.ts'
export * as internals from './internals.ts'

export type { RawData } from './methods/serialization.ts'
export type { Language } from './components/tokenizer/languages.ts'
