export * as radix from './trees/radix.js'
export * as avl from './trees/avl.js'
export * as zip from './trees/zip.js'
export * as bkd from './trees/bkd.js'
export * as flat from './trees/flat.js'
export * as bool from './trees/bool.js'
export * as vector from './trees/vector.js'
